# Generated by Django 6.0.3 on 2026-05-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_alter_registeration_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeration',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
